/**
 * Harness boundary exports.
 *
 * This module defines the reusable runtime surface that is expected to
 * become the future `dotcontext/harness` package. It intentionally excludes
 * CLI-only concerns and MCP transport adapters.
 */

export {
  WorkflowService,
  type WorkflowServiceDependencies,
  type WorkflowInitOptions,
  type WorkflowHarnessStatus,
  HarnessWorkflowBlockedError,
} from './application/workflow';
export {
  HarnessAdapterRuntime,
  HARNESS_HOOK_SOURCES,
  HARNESS_ADAPTER_TOOL_NAMES,
  HarnessHookAdapter,
  createHarnessHookAdapter,
  buildHookTraceData,
  classifyBashCommand,
  extractBashCommand,
  buildHookReadinessSummary,
  getHookReadinessSummary,
  extractHookReadinessSummary,
  formatHookReadinessAdditionalContext,
  consumeWorkflowMissingReminder,
  recordHookTraceFailure,
  readHookTraceFailures,
  type HarnessAdapterRuntimeOptions,
  type HarnessAdapterToolName,
  type HarnessAdapterInput,
  type HarnessAdapterRequest,
  type HarnessAdapterRuntimeResult,
  type HarnessHookSource,
  type HarnessHookEvent,
  type HarnessHookSuccessResponse,
  type HarnessHookErrorResponse,
  type HarnessHookResponse,
  type HarnessHookAdapterOptions,
  type HookBashClassification,
  type HookContextReadiness,
  type HookWorkflowReadiness,
  type HookWorkflowPreflightSummary,
  type HookReadinessSummary,
  type GetHookReadinessSummaryOptions,
  type HookReminderPolicy,
  type HookRemindersState,
  type HookTraceFailuresState,
  type HookTraceFailureRecord,
  type HookTraceFailureRecordResult,
  type HookTraceFailureSummary,
  type ConsumeWorkflowMissingReminderOptions,
  type RecordTraceFailureOptions,
  HarnessActionService,
  type HarnessActionServiceOptions,
  type HarnessAction,
  type HarnessActionInput,
  type HarnessActionResult,
  HarnessAgentActionService,
  type HarnessAgentActionServiceOptions,
  type HarnessAgentAction,
  type HarnessAgentActionInput,
  type HarnessAgentActionResult,
  HarnessSkillActionService,
  type HarnessSkillActionServiceOptions,
  type HarnessSkillAction,
  type HarnessSkillActionInput,
  type HarnessSkillActionResult,
  HarnessPlanActionService,
  type HarnessPlanActionServiceOptions,
  type HarnessPlanAction,
  type HarnessPlanActionInput,
  type HarnessPlanActionResult,
  HarnessExploreActionService,
  type HarnessExploreActionServiceOptions,
  type HarnessExploreAction,
  type HarnessExploreActionInput,
  type HarnessExploreActionResult,
  HarnessContextActionService,
  type HarnessContextActionServiceOptions,
  type HarnessContextAction,
  type HarnessContextActionInput,
  type HarnessContextActionResult,
  HarnessSyncActionService,
  type HarnessSyncActionServiceOptions,
  type HarnessSyncAction,
  type HarnessSyncActionInput,
  type HarnessSyncActionResult,
  HarnessWorkflowManageActionService,
  type HarnessWorkflowManageActionServiceOptions,
  type HarnessWorkflowManageAction,
  type HarnessWorkflowManageActionInput,
  type HarnessWorkflowManageActionResult,
  HarnessWorkflowActionService,
  type HarnessWorkflowActionServiceOptions,
  type HarnessWorkflowInitInput,
  type HarnessWorkflowStatusInput,
  type HarnessWorkflowGuideInput,
  type HarnessWorkflowAdvanceInput,
  type HarnessWorkflowActionResult,
  HarnessAgentsService,
  type HarnessAgentsServiceOptions,
  HarnessContextService,
  type HarnessContextServiceOptions,
  HarnessSkillsService,
  type HarnessSkillsServiceOptions,
  type HarnessBootstrapStatusResult,
  HarnessRuntimeStateService,
  type HarnessRuntimeStateServiceOptions,
  type HarnessSessionStatus,
  type HarnessTraceLevel,
  type HarnessArtifactKind,
  type HarnessSessionRecord,
  type HarnessSessionCheckpoint,
  type HarnessTraceRecord,
  type HarnessArtifactRecord,
  type HarnessRuntimeStatePort,
  type CreateSessionInput,
  type AppendTraceInput,
  type AddArtifactInput,
  type CheckpointInput,
  HarnessSensorsService,
  HarnessSensorCatalogService,
  type HarnessSensorsServiceOptions,
  type HarnessSensorCatalogServiceOptions,
  type HarnessSensorSeverity,
  type HarnessSensorStatus,
  type HarnessSensorExecutionInput,
  type HarnessSensorExecutionResult,
  type HarnessSensorDefinition,
  type HarnessSensorRun,
  type HarnessBackpressurePolicy,
  type HarnessBackpressureResult,
  type HarnessShellSensorConfig,
  type HarnessSensorCatalogDocument,
  type HarnessSensorCatalogSeverity,
  HarnessTaskContractsService,
  type HarnessTaskContractsServiceOptions,
  type HarnessTaskContractStatus,
  type HarnessTaskContract,
  type HarnessHandoffContract,
  type HarnessTaskCompletionResult,
  HarnessExecutionService,
  type HarnessExecutionServiceOptions,
  type HarnessSessionQualitySnapshot,
  HarnessReplayService,
  type HarnessReplayServiceOptions,
  type HarnessReplayDependencies,
  type HarnessReplayEvent,
  type HarnessReplayEventSource,
  type HarnessReplayRecord,
  type ReplaySessionOptions,
  HarnessDatasetService,
  type HarnessDatasetServiceOptions,
  type HarnessDatasetDependencies,
  type BuildHarnessDatasetOptions,
  type HarnessFailureKind,
  type HarnessFailureRecord,
  type HarnessFailureCluster,
  type HarnessFailureDataset,
  HarnessPolicyService,
  HarnessPolicyBlockedError,
  type HarnessPolicyServiceOptions,
  type HarnessPolicyTarget,
  type HarnessPolicyScope,
  type HarnessPolicyEffect,
  type HarnessPolicyRisk,
  type HarnessPolicyRule,
  type CreateHarnessPolicyRuleInput,
  type HarnessPolicyEvaluationInput,
  type HarnessPolicyEvaluationResult,
  HarnessWorkflowStateService,
  type HarnessWorkflowStateServiceOptions,
  type HarnessWorkflowRecord,
  type WorkflowHarnessBinding,
} from './application';
export {
  HarnessPlansService,
  type HarnessPlansServiceOptions,
} from './application/workflow/plansService';

export {
  getScaleName,
  PHASE_NAMES_PT,
  ROLE_DISPLAY_NAMES,
  type PrevcRole,
} from './domain/workflow';
