/**
 * Harness boundary exports.
 *
 * This module defines the reusable runtime surface that is expected to
 * become the future `dotcontext/harness` package. It intentionally excludes
 * CLI-only concerns and MCP transport adapters.
 */

export {
  WorkflowService,
  type WorkflowServiceDependencies,
  type WorkflowInitOptions,
  type WorkflowHarnessStatus,
  HarnessWorkflowBlockedError,
} from '../services/workflow';
export {
  HarnessAgentsService,
  type HarnessAgentsServiceOptions,
  HarnessPlansService,
  type HarnessPlansServiceOptions,
  HarnessContextService,
  type HarnessContextServiceOptions,
  HarnessSkillsService,
  type HarnessSkillsServiceOptions,
  HarnessRuntimeStateService,
  type HarnessRuntimeStateServiceOptions,
  type HarnessSessionStatus,
  type HarnessTraceLevel,
  type HarnessArtifactKind,
  type HarnessSessionRecord,
  type HarnessSessionCheckpoint,
  type HarnessTraceRecord,
  type HarnessArtifactRecord,
  type HarnessRuntimeStatePort,
  type CreateSessionInput,
  type AppendTraceInput,
  type AddArtifactInput,
  type CheckpointInput,
  HarnessSensorsService,
  type HarnessSensorsServiceOptions,
  type HarnessSensorSeverity,
  type HarnessSensorStatus,
  type HarnessSensorExecutionInput,
  type HarnessSensorExecutionResult,
  type HarnessSensorDefinition,
  type HarnessSensorRun,
  type HarnessBackpressurePolicy,
  type HarnessBackpressureResult,
  HarnessTaskContractsService,
  type HarnessTaskContractsServiceOptions,
  type HarnessTaskContractStatus,
  type HarnessTaskContract,
  type HarnessHandoffContract,
  type HarnessTaskCompletionResult,
  HarnessExecutionService,
  type HarnessExecutionServiceOptions,
  type HarnessSessionQualitySnapshot,
  HarnessReplayService,
  type HarnessReplayServiceOptions,
  type HarnessReplayDependencies,
  type HarnessReplayEvent,
  type HarnessReplayEventSource,
  type HarnessReplayRecord,
  type ReplaySessionOptions,
  HarnessDatasetService,
  type HarnessDatasetServiceOptions,
  type HarnessDatasetDependencies,
  type BuildHarnessDatasetOptions,
  type HarnessFailureKind,
  type HarnessFailureRecord,
  type HarnessFailureCluster,
  type HarnessFailureDataset,
  HarnessPolicyService,
  HarnessPolicyBlockedError,
  type HarnessPolicyServiceOptions,
  type HarnessPolicyTarget,
  type HarnessPolicyScope,
  type HarnessPolicyEffect,
  type HarnessPolicyRisk,
  type HarnessPolicyRule,
  type CreateHarnessPolicyRuleInput,
  type HarnessPolicyEvaluationInput,
  type HarnessPolicyEvaluationResult,
} from '../services/harness';

export {
  getScaleName,
  PHASE_NAMES_PT,
  ROLE_DISPLAY_NAMES,
  type PrevcRole,
} from '../workflow';
