import * as path from 'path';
import * as fs from 'fs-extra';
import type { AgentFileInfo, HandlerOptions, HandlerResult } from './types';

function getTargetFilename(agent: AgentFileInfo, options: HandlerOptions): string {
  const suffix = options.filenameSuffix || '';
  return `${agent.name}${suffix}.md`;
}

export async function createMarkdownReferences(
  agentFiles: AgentFileInfo[],
  targetPath: string,
  sourcePath: string,
  options: HandlerOptions
): Promise<HandlerResult> {
  const result: HandlerResult = {
    filesCreated: 0,
    filesSkipped: 0,
    filesFailed: 0,
    errors: []
  };

  for (const agent of agentFiles) {
    const targetFilename = getTargetFilename(agent, options);
    const refPath = path.join(targetPath, targetFilename);

    try {
      const exists = await fs.pathExists(refPath);

      if (exists && !options.force) {
        result.filesSkipped++;
        if (options.verbose) {
          console.log(`  Skipped (exists): ${refPath}`);
        }
        continue;
      }

      if (!options.dryRun) {
        const relativePath = path.relative(targetPath, agent.sourcePath);
        const content = generateReferenceMarkdown(agent, relativePath, sourcePath);
        await fs.writeFile(refPath, content);
      }

      result.filesCreated++;

      if (options.verbose) {
        console.log(`  Created: ${refPath}`);
      }
    } catch (error) {
      result.filesFailed++;
      result.errors.push({
        file: targetFilename,
        error: error instanceof Error ? error.message : String(error)
      });
    }
  }

  return result;
}

function generateReferenceMarkdown(
  agent: AgentFileInfo,
  relativePath: string,
  sourcePath: string
): string {
  const title = formatAgentTitle(agent.name);
  const timestamp = new Date().toISOString();

  return `# ${title} Agent

> **Source**: [${agent.filename}](${relativePath})
>
> This is a reference file. The canonical agent definition is maintained in \`.context/agents/\`.

---

<!--
  AUTO-GENERATED REFERENCE FILE

  This file references the canonical agent playbook at:
  ${sourcePath}/${agent.filename}

  To update the agent, edit the source file directly.
  Re-run 'dotcontext sync-agents' to regenerate this reference.

  Generated: ${timestamp}
-->

## Quick Reference

- **Agent Type**: ${agent.name}
- **Source Location**: \`${sourcePath}/${agent.filename}\`
- **Reference Path**: \`${relativePath}\`

## Usage

This agent playbook can be accessed via the source file linked above.
The source file contains the full agent definition including:

- Mission and responsibilities
- Best practices
- Key project resources
- Repository starting points
- Documentation touchpoints
- Collaboration checklist

## See Also

- [Full Agent Playbook](${relativePath})

---
*Generated by Dotcontext*
*Last synced: ${timestamp}*
`;
}

function formatAgentTitle(name: string): string {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
